config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :categories do
    resources :payments
  end
  root 'splashes#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :manage, :all
    can :manage, :all

    return unless user.present?

    can(:destroy, Category, user:)
    can :destroy, Payment, user:
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: 'user_id'
  has_many :payments, dependent: :destroy, foreign_key: 'category_id'
  has_one_attached :image, dependent: :destroy

  validates :name, presence: true
  validates :image, presence: true
  validates :user_id, presence: true

  def self.search(search)
    where('name LIKE ?', "%#{search}%")
  end
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :user
  belongs_to :category, dependent: :destroy

  validates :name, :amount, presence: true

  def self.search(search)
    where('name LIKE ?', "%#{search}%")
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :categories
  has_many :payments
  has_one_attached :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :update_allowed_parameters, if: :devise_controller?
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, alert: exception.message
  end

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:name, :email, :password, :image)
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category, only: %i[show edit update destroy]

  def index
    @categories = Category.where(user_id: current_user.id)
  end

  def show
    @payments = Payment.where(category_id: params[:id]).order('created_at DESC')
  end

  def new
    @category = Category.new
  end

  def edit; end

  def create
    @category = Category.new(category_params)
    @category.user_id = current_user.id
    if @category.save
      flash[:notice] = 'Category was successfully created.'
      redirect_to new_category_payment_url(@category)
    else
      flash[:alert] = 'Category was not created.'
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    flash[:notice] = 'Category was successfully deleted.'
    redirect_to categories_path
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :image)
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_payment, only: %i[show edit update destroy]

  def index
    @category = Category.find(params[:category_id])
    @payment = Payment.where(category_id: params[:category_id]).order('created_at DESC')
  end

  def show
    @payment = Payment.find(params[:id])
  end

  def new
    @payment = Payment.new
    @categories = Category.where(user_id: current_user.id)
  end

  def edit; end

  def create
    @user = current_user
    @payment = @user.payments.new(payment_params)
    if @payment.save
      flash[:notice] = 'Payment was successfully created.'
      redirect_to categories_path
    else
      flash[:alert] = 'Payment was not created.'
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @payment = Payment.find(params[:id])
    @payment.destroy
    flash[:notice] = 'Payment was successfully deleted.'
    redirect_to new_category_payment_path
  end

  private

  def set_payment
    @payment = Payment.includes(:user, :category).find(params[:id])
  end

  def payment_params
    params.require(:payment).permit(:name, :amount, :category_id, :user_id)
  end
end

app/controllers/splashes_controller.rb
class SplashesController < ApplicationController
  def index
    redirect_to categories_path if user_signed_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/splashes_helper.rb
module SplashesHelper
end

app/views/categories/index.html.erb
<header class=" bg-mySpend px-2 h-16 sm:px-4 py-2 sm:py-0 sticky w-full flex justify-center z-20 top-0 left-0">
  <nav class="container flex flex-wrap sm:flex-nowrap justify-between p-0 items-center mx-auto">
    <span><%= image_tag('avatar', class:"h-10 w-10 p-0 m-auto") %></span>
    <% if user_signed_in? %>
    <% end %>
    <span class="text-center text-white text-md">CATEGORIES</span>
    <span>
      <% if user_signed_in? %>
        <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'text-white text-center'  %>
      <% else %>
        <%= link_to "Sign Up", new_user_registration_path, :class => 'text-white text-center' %>
        <%= f.submit "Sign In", class: "text-white text center" %>
      <% end %>
    </span>
  </nav>
</header>
<div class="container w-56 h-auto py-4 mb-16 relative ">
  <% if user_signed_in? %>
    <% @categories.each do |category| %>
      <div class="card-body md:mt-8 lg:mt-12 flex w-auto justify-between items-center p-2 mb-4 rounded-sm border shadow-md">
        <div class="flex justify-start w-auto gap-2">
          <%= link_to category_path(category) do %>
            <% if category.image.attached? %>
              <%= image_tag category.image, skip_pipeline: true, alt: 'category icon', class: "h-16 w-16 rounded-sm" %>
            <% end %>
          <% end %>
          <span class="flex flex-col justify-between">
            <%= link_to category.name, category_path(category), :class => "text-mySpend-Text text-lg font-bold" %>
            <span class="text-xs text-gray">
              <%= category.created_at.strftime("%d/%m/%Y") %> at <%= category.created_at.strftime("%H:%M") %>
            </span>
          </span>
        </div>
        <div class="flex flex-col justify-end items-end">
          <p class="price text-mySpend-Text">
            $<%= category.payments.sum(:amount) %>
          </p>
          <% if category.payments.empty? %>
            <span><%= button_to "Add Payment", new_category_payment_path(category), method: :get, :class => "text-mySpend" %></span>
          <% else %>
            <span><%= button_to "Delete",  category_path(category), method: :delete, :class => "text-danger"  %></span>
          <% end %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>
<% if can? :create, @category %>
<span class="w-full rounded-0 fixed bottom-0 z-20 text-center p-2 bg-mySpend-green">
<%= link_to "New category", new_category_path, class: "btn border rounded-0 border-white p-2 text-white text-md text-center" %>
</span>
<% end %>

app/views/categories/new.html.erb
<%= form_with(model: @category) do |form| %>
<header class=" bg-mySpend px-2 h-16 sm:px-4 py-2 sm:py-0 sticky w-full flex justify-center z-20 top-0 left-0">
  <nav class="container flex flex-wrap sm:flex-nowrap justify-between p-0 items-center mx-auto">
    <span><%= link_to image_tag('arrow_left.svg', class:"h-6 w-6 p-0 m-auto"), categories_path %></span>
    <span class="text-center text-white text-md">ADD CATEGORIES</span>
    <span>
      <% if user_signed_in? %>
        <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'text-white text-center'  %>
      <% else %>
        <%= link_to "Sign Up", new_user_registration_path, :class => 'text-white text-center' %>
        <%= f.submit "Sign In", class: "text-white text center" %>
      <% end %>
    </span>
  </nav>
</header>
<div class="container p-0">
  <div class="card-body bg-white shadow-md">
    <%= form.text_field :name, placeholder: "Name", class: "field w-full py-2 px-1 mb-3 bg-transparent text-md" %>
    <%=form.file_field :image, class: "field w-full py-2 px-1 mb-3 bg-transparent text-md" %>
    <%= button_to "SAVE", categories_path, method: :post, :class => "btn bg-primary w-32 text-white" %>
  </div>
</div>
<% end %>

app/views/categories/show.html.erb
<header class=" bg-mySpend px-2 h-16 sm:px-4 py-2 sm:py-0 sticky w-full flex justify-center z-20 top-0 left-0">
  <nav class="container flex flex-wrap sm:flex-nowrap justify-between p-0 items-center mx-auto">
    <span><%= link_to image_tag('arrow_left.svg', class:"h-6 w-6 p-0 m-auto"), categories_path %></span>
    <span class="text-center text-white text-md">PAYMENTS</span>
    <span>
      <% if user_signed_in? %>
        <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'text-white text-center'  %>
      <% else %>
        <%= link_to "Sign Up", new_user_registration_path, :class => 'text-white text-center' %>
        <%= f.submit "Sign In", class: "text-white text center" %>
      <% end %>
    </span>
  </nav>
</header>
<div class="container">
  <% if @payments.exists? %>
    <div class="container p-0 w-full h-auto">
      <% @payments.each do |payment| %>
        <div class="container h-auto mt-4 md:mt-8 lg:mt-12 flex justify-between items-center bg-light border rounded-md shadow-md">
          <div class="flex flex-col">
            <span class="text-mySpend-Text fw-600 mb-2 text-lg">
              <%= payment.name %>
            </span>
            <span class="text-mySpend-TextLight">
              <%= payment.created_at.strftime("%d/%m/%Y") %> at <%= payment.created_at.strftime("%H:%M") %>
            </span>
          </div>
          <span class="text-mySpend-TextLight text-lg">
            $<%= payment.amount %>
          </span>
        </div>
      <% end %>
    </div>
    <% else %>
      <span>
        <h2 class="text-center text-mySpend-Text text-xl mt-48">No Payments Available Now! <br />Click the button bellow to add a new payment.</h2>
        <%= image_tag('arrowDown.svg', :alt => "arrow down icon", class:"h-10 w-10 p-0 fw-bold mx-auto mt-4") %>
      </span>
    <% end %>
</div>
  <span class="w-full rounded-0 fixed bottom-0 z-20 text-center p-2 bg-mySpend-green">
    <%= link_to "New Payment", new_category_payment_path(@category), class: "btn border rounded-0 border-white p-2 text-white text-md text-center" %>
  </span>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ExpenseTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
<%= javascript_importmap_tags %>
  </head>

<body class="bg-light">
  <main class="root container-fluid p-0 h-auto">
    <%= yield %>
      <% if notice %>
        <div class="flex flex-col justify-center items-center container-fluid fixed z-50 w-10/12 md:w-8/12 lg:w-6/12 bg-transparent px-4 top-1/3 left-1/12 right-1/12 py-2 rounded" role="alert">
          <div class="container bg-white h-64 py-2 shadow-md">
            <span class='flex justify-end items-center rounded-md'>
              <%= button_to image_tag('close_button'), new_category_path(@category), class: "close w-5 h-5 rounded-full text-center items-center", data_dismiss: "alert" %>
            </span>
            <div class="flex flex-col w-full flex-wrap justify-center items-center mb-4 pt-4">
              <span><%= image_tag "complete_check.svg", alt: 'complete icon', class: "w-16 h-16 rounded-full bg-mySpend-green mb-2" %></span>
              <h4>Complete</h4>
              <span class="notice block text-center"><%= notice %></span>
            </div>
          </div>
        </div>
      <% end %>
      <% if alert %>
        <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert">
          <span class="alert block sm:inline"><%= alert %></span>
        </div>
      <% end %>
  </main>
</body>
</html>

app/views/payments/new.html.erb
  <header class=" bg-mySpend px-2 h-16 sm:px-4 py-2 sm:py-0 sticky w-full flex justify-center z-20 top-0 left-0">
    <nav class="container flex flex-wrap sm:flex-nowrap justify-between p-0 items-center mx-auto">
      <span><%= link_to image_tag('arrow_left.svg', class:"h-6 w-6 p-0 m-auto"), new_user_registration_path %></span>
      <span class="text-center text-white text-md">PAYMENTS</span>
      <span>
        <% if user_signed_in? %>
          <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'text-white text-center'  %>
        <% else %>
          <%= link_to "Sign Up", new_user_registration_path, :class => 'text-white text-center' %>
          <%= f.submit "Sign In", class: "text-white text center" %>
        <% end %>
      </span>
    </nav>
  </header>
<%= form_with model:  @payment, url: category_payments_path(@categories) do |f| %>
  <div class="card-body error-message">
    <% if @payment.errors.any? %>
      <ul class="list-style-none p-0">
        <% @payment.errors.full_messages.each do |message| %>
          <li class="text-danger fw-md text-ms text-center">* <%= message %></li>
        <% end %>
      </ul>
    <% end %>
  </div>
  <div class="card-body bg-white form shadow-md">
    <%= f.text_field :name, placeholder: "Payment name", class: "field w-full py-2 px-1 mb-3 bg-transparent outline outline-offset-0 outline-0", autofocus: true, autocomplete: "off", required: true %>
    <%= f.text_field :amount, placeholder: "Amount", class: "field w-full py-2 px-1 mb-3 bg-transparent", autofocus: true, autocomplete: "off", required: true %>
    <%= f.collection_select :category_id, @categories, :id, :name, {prompt: "Select Category"}, {class: "field w-full py-2 px-1 mb-3 bg-transparent", required: true} %>
    <div class="button-form">
      <%= f.submit "Create Payment", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/splashes/index.html.erb
    <div class="card z-50 top-0 h-screen bg-mySpend-splash flex flex-col justify-center align-items-center">
      <h1 class="text-mySpend font-medium text-5xl -mt-24 md:text-9xl text-center">Expense <span class="text-mySpend-green">Tracker</span></h1>
      <div class="container w-full absolute bottom-12 md:relative md:mt-16 md:px-0 md:flex md:justify-center align-items-center md:gap-4 space-y-4 md:space-y-0">
          <%= button_to "LOG IN", new_user_session_path, method: :get, :class => "bg-mySpend w-full md:w-auto py-2 md:px-6 text-white" %>
          <%= button_to "SIGN UP", new_user_registration_path, method: :get, :class => "bg-transparent w-full md:w-auto py-2 md:px-6 border border-mySpend text-mySpend-Text md:text-mySpend-Text" %>
      </div>
    </div>